let EPITA = 1
let mapleader=","

set t_Co=256
set background=dark

filetype off

"set rtp+=~/.vim/bundle/vundle/
"call vundle#rc()

"Bundle 'gmarik/vundle'
"
call plug#begin('~/.vim/plugged')

" Github bundles
Plug 'junegunn/vim-easy-align'
Plug 'Valloric/ListToggle'
Plug 'scrooloose/syntastic'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'Lokaltog/vim-easymotion'
Plug 'msanders/snipmate.vim'
Plug 'tpope/vim-fugitive'
Plug 'bling/vim-airline'
Plug 'bling/vim-bufferline'
Plug 'kien/ctrlp.vim'
Plug 'majutsushi/tagbar'
Plug 'chrisbra/csv.vim'
Plug 'airblade/vim-gitgutter'
Plug 'sjl/gundo.vim'
Plug 'edkolev/promptline.vim'
Plug 'edkolev/tmuxline.vim'
Plug 'rkitover/vimpager'
Plug 'aklt/plantuml-syntax'
Plug 'wting/rust.vim'
Plug 'klen/python-mode'
Plug 'xolox/vim-misc'
Plug 'xolox/vim-easytags'
" colorschemes
Plug 'romainl/Apprentice'
" vim-scripts bundles
Plug 'L9'
Plug 'FuzzyFinder'
Plug 'repeat.vim'
Plug 'surround.vim'
Plug 'a.vim'

call plug#end()

filetype plugin indent on

if has("syntax")
    syntax on
endif
if has("gui_running")
    set guifont=Ubuntu\ Mono\ For\ Powerline\ 10
    colorscheme desert
    set guioptions-=m
    set guioptions-=T
    set guioptions-=r
else
    colorscheme calops-molokai
endif

" CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

" airline
let g:airline_powerline_fonts=0
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_theme='badwolf'
let g:airline#extensions#bufferline#enabled = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#whitespace#enabled = 1
let g:airline#extensions#whitespace#checks = [ 'indent', 'trailing' ]
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#tmuxline#enabled = 0
let g:airline#extensions#tagbar#enabled = 0

" clipboard
set clipboard+=unnamed,unnamedplus

" tmuxline
let g:tmuxline_powerline_separators = 0

" gundo
nnoremap <F5> :GundoToggle<CR>

" NERD tree
map <F2> :NERDTreeToggle<CR>

" ListToggle
let g:lt_location_list_toggle_map = '<leader>l'
let g:lt_quickfix_list_toggle_map = '<leader>q'

" Tagbar
nmap <F8> :TagbarToggle<CR>

" bufferline
let g:bufferline_show_bufnr = 1

" pymode
let g:pymode_options_max_line_length = 120
let g:pymode_lint_unmodified = 1
let g:pymode_lint_sort = ['E', 'W', 'C', 'I']
let g:pymode_trim_whitespaces = 0

" syntastic
let g:syntastic_c_check_header = 1
let g:syntastic_cpp_check_header = 1

" project-specific conf file
set exrc
set secure

" easytags
let g:easytags_async = 1
let g:easytags_syntax_keyword = 'always'
let g:easytags_auto_highlight = 0

" backup
set backup
set backupdir=~/.vimtmp/backup
set directory=~/.vimtmp/temp

silent !mkdir -p ~/.vimtmp/backup
silent !mkdir -p ~/.vimtmp/temp

if version >= 703
    set undofile
    set undodir=~/.vimtmp/undo
    silent !mkdir -p ~/.vimtmp/undo
endif

" compatibility
set nocompatible

set backspace=eol,indent,start
set showmode showcmd

" editzone
set number
set laststatus=2
set wildmenu
set hidden
set noerrorbells
set novisualbell
set cursorline
if version >= 703
    set colorcolumn+=1
endif
set list
set listchars=tab:·\ ,eol:¬

" encoding
set encoding=utf-8
if exists("g:modifiable_on")
    set fileencoding=utf-8
end

" search
set hlsearch
set incsearch
set smartcase
set ignorecase
set gdefault
set showmatch
:nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

" C/C++
au Bufnewfile,Bufread *.h set filetype=c
au BufNewFile,BufRead *.{cpp,hh,hxx,cc,hpp} set filetype=cpp

" python
if has('syntax')
    let python_highlight_builtins = 1
    let python_highlight_exceptions = 1
    let python_highlight_space_errors = 1
endif

" indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab
set autoindent smartindent

" mouse
set mouse=a

" whitespaces
highlight ExtraWhitespace ctermbg=lightgreen
autocmd BufNew * match ExtraWhitespace /\s\+$/
command TrimSpaces %s/\s\+$//

" viminfo
set viminfo='20,\"50

" wrapping
set wrap
set textwidth=0
set colorcolumn=120

" tabs
set et
set ts=4
set sts=4
set sw=4

" comments format
setlocal comments=sl:/*,mb:**,elx:*/


" bindings
inoremap <F1> <esc>
vnoremap <F1> <esc>
nnoremap <F1> <esc>
vmap <C-c> "+y
nnoremap ; :
