# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="calops"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=2

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git
         autopep8
         docker
         gradle
         mosh
         postgres
         python
         sudo
         tmux
         cp
         themes
         vundle
         truegit
         common-aliases)

export GOPATH=/var/go
export PATH="$HOME/.local/bin:$HOME/usr/sbin:$HOME/usr/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/usr/lib;$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH="$HOME/usr/lib/pkgconfig"
export PYTHONPATH="$PYTHONPATH:$HOME/config/local/python2.7/site-packages/powerline:$HOME/usr/lib/python2.7/site-packages:$HOME/config/python"

source $ZSH/oh-my-zsh.sh

# User configuration

# Variables
export LC_ALL="en_US.UTF-8"
export http_proxy="http://vpprx02:3128"
export https_proxy="http://vpprx02:3128"
export EDITOR=vim
export PAGER=vimpager
export FULLNAME="Rémi Labeyrie"
export NAME="calops"
export EMAIL="calops@wibblywobbly.net"
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM=verbose
export GIT_PS1_DESCRIBE_STYLE=branch
export GIT_PS1_SHOWCOLORHINTS=1
LS_COLORS="\
*=37:\
\
di=1;34:\
ln=4;94:\
ex=91:\
\
*.txt=32:\
*README=1;32:\
*README.txt=1;32:\
*TODO=32:\
*ChangeLog=32:\
*AUTHORS=32:\
*CONTRIBUTORS=32:\
*LICENSE=32:\
*PKG-INFO=32:\
*NEWS=32:\
*COPYING=32:\
*COPYRIGHT=32:\
\
*Makefile=95:\
\
*.h=33:\
*.hpp=33:\
*.c=93:\
*.hh=33:\
*.cc=93:\
*.cpp=93:\
*.hxx=93:\
\
*.tar=96:\
*.gz=96:\
*.bz2=96:\
*.tbz=96:\
*.tgz=96:\
*.7z=96"
export LS_COLORS

case "$TERM" in
    rxvt-unicode*)
        export TERM=rxvt
    ;;
esac

# Aliases
alias rm='rm -i'
alias rmf='rm -rf'
alias tmux='tmux -u2'

# Misc
setopt transient_rprompt
